import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  RedirectToSignIn,
  
} from '@clerk/nextjs'
import { ButtonAsChild } from "../app/Button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/'>
      <html lang="en">
        <body className="antialiased">
          {/* <header className="flex justify-end items-center p-4 gap-4 h-4"> */}
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            {/* <SignedIn> */}
              {/* <UserButton /> */}
            {/* </SignedIn> */}
          {/* </header> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
